#Requires -Version 5.1
<#
    Install / refresh the ITAM repo auto-sync.

    It does four things:
      1. locate bash.exe and node.exe (no hardcoded versioned paths)
      2. write scripts\repo-sync-run.cmd  (the entry point a task can call)
      3. set core.hooksPath = .githooks    (so post-commit pushes immediately)
      4. register a scheduled task that runs scripts\repo-sync.sh every N minutes

    Usage (normal PowerShell is enough for the default interactive task):
      powershell -ExecutionPolicy Bypass -File scripts\install-repo-sync.ps1

    Run as Administrator if you want the task to fire while nobody is logged on:
      powershell -ExecutionPolicy Bypass -File scripts\install-repo-sync.ps1 -RunWhenLoggedOff

    Other switches:
      -Status            show the task state and the last sync result, then exit
      -Remove            unregister the task, then exit
      -NoTask            do steps 1-3 only
      -IntervalMinutes N  default 5

    NOTE: this file is intentionally ASCII-only. Windows PowerShell 5.1 reads
    BOM-less .ps1 as ANSI and would garble non-ASCII text.
#>
[CmdletBinding()]
param(
  [string]$TaskName = 'ITAM-Repo-Sync',
  [int]$IntervalMinutes = 5,
  [switch]$Status,
  [switch]$Remove,
  [switch]$NoTask,
  [switch]$RunWhenLoggedOff
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$Runner = Join-Path $PSScriptRoot 'repo-sync-run.cmd'
$LogDir = Join-Path $Root 'logs'
$SyncLog = Join-Path $LogDir 'repo-sync.log'
$SyncStatus = Join-Path $LogDir 'repo-sync-status.txt'

function Write-Step($t) { Write-Host "[repo-sync] $t" }
function Write-Warn2($t) { Write-Host "[repo-sync] $t" -ForegroundColor Yellow }

function Find-Bash {
  $cmd = Get-Command bash.exe -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $globs = @(
    (Join-Path $env:USERPROFILE '.workbuddy\binaries\PortableGit\versions\*\usr\bin\bash.exe'),
    (Join-Path $env:USERPROFILE '.workbuddy\binaries\PortableGit\versions\*\bin\bash.exe'),
    "$env:ProgramFiles\Git\bin\bash.exe",
    "${env:ProgramFiles(x86)}\Git\bin\bash.exe",
    "$env:LOCALAPPDATA\Programs\Git\bin\bash.exe"
  )
  foreach ($g in $globs) {
    $hit = Get-ChildItem -Path $g -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($hit) { return $hit.FullName }
  }
  return $null
}

function Find-Node {
  $cmd = Get-Command node.exe -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $globs = @(
    (Join-Path $env:USERPROFILE '.workbuddy\binaries\node\versions\*\node.exe'),
    "$env:ProgramFiles\nodejs\node.exe"
  )
  foreach ($g in $globs) {
    $hit = Get-ChildItem -Path $g -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($hit) { return $hit.FullName }
  }
  return $null
}

# ---------------------------------------------------------------- status
if ($Status) {
  Write-Step "task '$TaskName':"
  $t = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($t) {
    Write-Host ("  state      : " + $t.State)
    $i = Get-ScheduledTaskInfo -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($i) {
      Write-Host ("  last run   : " + $i.LastRunTime + "   result: " + $i.LastTaskResult)
      Write-Host ("  next run   : " + $i.NextRunTime)
    }
  } else {
    Write-Warn2 "  not registered yet"
  }
  if (Test-Path $SyncStatus) {
    Write-Step "last sync :"
    Get-Content $SyncStatus | ForEach-Object { Write-Host ("  " + $_) }
  } else {
    Write-Host "[repo-sync] no sync has run yet"
  }
  if (Test-Path $SyncLog) {
    Write-Step "log tail ($SyncLog):"
    Get-Content $SyncLog -Tail 12 | ForEach-Object { Write-Host ("  " + $_) }
  }
  exit 0
}

# ---------------------------------------------------------------- remove
if ($Remove) {
  if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Step "task '$TaskName' removed"
  } else {
    Write-Warn2 "task '$TaskName' was not registered"
  }
  exit 0
}

# ---------------------------------------------------------------- 1. tools
$bash = Find-Bash
if (-not $bash) { throw "bash.exe not found. Install Git for Windows, or run this from Git Bash." }
Write-Step "bash : $bash"

$node = Find-Node
if (-not $node) { Write-Warn2 "node.exe not found - the security gate needs it, sync will be blocked" }
else { Write-Step "node : $node" }

# ---------------------------------------------------------------- 2. runner
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

$runnerText = @"
@echo off
rem Generated by scripts\install-repo-sync.ps1 - machine specific, git-ignored.
rem ASCII-only on purpose: cmd.exe reads .cmd in the OEM codepage, so non-ASCII
rem comments get mangled and can be parsed as bogus commands.
setlocal
rem NOTE the trailing backslash: %~dp0.. does not end with a separator, and
rem without it the path below would concatenate into ".../scripts/..scripts/..."
set "ROOT=%~dp0..\"
set "BASH=$bash"
"%BASH%" -l "%ROOT:\=/%scripts/repo-sync.sh"
exit /b %ERRORLEVEL%
"@
Set-Content -Path $Runner -Value $runnerText -Encoding ASCII
Write-Step "runner written: $Runner"

# quick smoke test: --status must exit 0
try {
  & cmd.exe /c $Runner '--status' | Out-Null
  Write-Step "runner smoke test: OK"
} catch {
  Write-Warn2 "runner smoke test failed: $($_.Exception.Message)"
}

# ---------------------------------------------------------------- 3. hooks
Push-Location $Root
try {
  & git config core.hooksPath .githooks
  if ($LASTEXITCODE -ne 0) { Write-Warn2 "could not set core.hooksPath (is git on PATH?)" }
  else { Write-Step "core.hooksPath = .githooks" }

  $sshCmd = & git config --get core.sshCommand
  if (-not $sshCmd) {
    Write-Warn2 "core.sshCommand is not set - push will use the default key and may fail"
  } else {
    Write-Step "core.sshCommand = $sshCmd"
  }
} finally { Pop-Location }

# ---------------------------------------------------------------- 4. task
if ($NoTask) { Write-Step "-NoTask given, skipping task registration"; exit 0 }

$logon = 'Interactive'
if ($RunWhenLoggedOff) { $logon = 'S4U' }

$action = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument ("/c `"$Runner`"") -WorkingDirectory $Root
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
  -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes) `
  -RepetitionDuration (New-TimeSpan -Days 3650)
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType $logon -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -StartWhenAvailable `
  -ExecutionTimeLimit (New-TimeSpan -Minutes 10) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

try {
  Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null
  Write-Step "task '$TaskName' registered, every $IntervalMinutes min (logon type: $logon)"
  $i = Get-ScheduledTaskInfo -TaskName $TaskName
  Write-Step "next run: $($i.NextRunTime)"
} catch {
  Write-Warn2 "could not register the task: $($_.Exception.Message)"
  Write-Warn2 "re-run this script from an elevated PowerShell prompt."
  exit 1
}

Write-Host ''
Write-Host 'Done. Reminder: the sync can only push after the SSH key is authorised:'
Write-Host '  1. copy the public key:  Get-Content "$env:USERPROFILE\.ssh\id_ed25519_itam.pub"'
Write-Host '  2. add it at https://github.com/settings/keys (Add SSH key)'
Write-Host '  3. verify:  & bash -lc "git -C ''<repo>'' ls-remote origin"'
Write-Host '  4. run once by hand:  powershell -File scripts\install-repo-sync.ps1 -Status'
