/**
 * 品牌知识库 —— 用于「拍照识别设备品牌」
 *
 * 结构：每个品牌包含
 *   name    规范中文/主名称
 *   en      英文名
 *   aliases 铭牌上可能出现的各种写法（会被模糊匹配）
 *   snPrefixes 该品牌 SN 常见前缀（用于从 SN 反推品牌）
 */
export const BRANDS = [
  { name: '戴尔', en: 'Dell', aliases: ['DELL', '戴尔', 'DELLINC', 'ALIENWARE', '外星人', 'dell tech'], snPrefixes: ['CN', 'DL', 'D', 'FVF', 'JH', 'B9', 'C0', 'G3', 'H0', 'SN'] },
  { name: '惠普', en: 'HP', aliases: ['HP', 'HPE', 'HEWLETTPACKARD', '惠普', 'COMPAQ', '康柏'], snPrefixes: ['CN', 'VNC', 'SGH', 'MXL', '5CG', 'CZC', 'JP', 'P5S'] },
  { name: '联想', en: 'Lenovo', aliases: ['LENOVO', '联想', 'THINKPAD', 'THINKCENTRE', 'IDEAPAD', 'LEGION', '拯救者', 'THINKBOOK', 'THINKSERVER'], snPrefixes: ['PF', 'PC', 'MJ', 'MP', 'LR', 'YB', 'R9', 'IN'] },
  { name: '华硕', en: 'ASUS', aliases: ['ASUS', '华硕', 'ASUSTEK', 'ROG', '玩家国度', 'TUF'], snPrefixes: ['AS', 'R6', 'J1'] },
  { name: '宏碁', en: 'Acer', aliases: ['ACER', '宏碁', '宏基', 'PREDATOR', '掠夺者', 'GATEWAY'], snPrefixes: ['NX', 'DM', 'A1'] },
  { name: '苹果', en: 'Apple', aliases: ['APPLE', '苹果', 'MACBOOK', 'IMAC', 'MACMINI', 'MACPRO', 'IPHONE', 'IPAD', 'MACKBOOK'], snPrefixes: ['FV', 'C0', 'C1', 'C2', 'C3', 'C7', 'DMP', 'F1', 'F2', 'G6', 'H2', 'W8'] },
  { name: '三星', en: 'Samsung', aliases: ['SAMSUNG', '三星', 'SAMSUNGELECTRONICS', 'GALAXY'], snPrefixes: ['RZ', 'RF', 'S24'] },
  { name: 'LG', en: 'LG', aliases: ['LG', 'LGELECTRONICS', 'LGELECTRONICSINC', '乐金'], snPrefixes: ['K1', 'L1'] },
  { name: '飞利浦', en: 'Philips', aliases: ['PHILIPS', '飞利浦', 'PHILIPSELECTRONICS'], snPrefixes: ['PH', 'UK'] },
  { name: 'AOC', en: 'AOC', aliases: ['AOC', '冠捷', 'TPV', 'AOCMONITOR'], snPrefixes: ['AOC', 'TPV'] },
  { name: '明基', en: 'BenQ', aliases: ['BENQ', '明基', 'BENQSE'], snPrefixes: ['ET', 'BQ'] },
  { name: '优派', en: 'ViewSonic', aliases: ['VIEWSONIC', '优派'], snPrefixes: ['VS', 'VX'] },
  { name: '华三', en: 'H3C', aliases: ['H3C', 'H3CTECHNOLOGIES', '华三', '新华三'], snPrefixes: ['2102', 'CN'] },
  { name: '华为', en: 'Huawei', aliases: ['HUAWEI', '华为', 'HONOR', '荣耀', 'MATEBOOK', 'MATE'], snPrefixes: ['HW', '2AB', '8DN', 'E3'] },
  { name: '小米', en: 'Xiaomi', aliases: ['XIAOMI', '小米', 'REDMI', '红米', 'MI', 'POCO'], snPrefixes: ['XM', 'MI', '2ABC'] },
  { name: 'OPPO', en: 'OPPO', aliases: ['OPPO', 'REALME', 'ONEPLUS', '一加'], snPrefixes: ['OP'] },
  { name: 'VIVO', en: 'vivo', aliases: ['VIVO', 'IQOO'], snPrefixes: ['VV'] },
  { name: '中兴', en: 'ZTE', aliases: ['ZTE', '中兴'], snPrefixes: ['ZT'] },
  { name: '爱普生', en: 'Epson', aliases: ['EPSON', '爱普生', 'SEIKOEPSON'], snPrefixes: ['EP', 'X4'] },
  { name: '佳能', en: 'Canon', aliases: ['CANON', '佳能'], snPrefixes: ['CN', 'KA'] },
  { name: '兄弟', en: 'Brother', aliases: ['BROTHER', '兄弟', 'BROTHERINDUSTRIES'], snPrefixes: ['BR', 'U6'] },
  { name: '富士施乐', en: 'Fuji Xerox', aliases: ['FUJIXEROX', '富士施乐', 'XEROX', '施乐', 'FUJIFILM'], snPrefixes: ['FX', 'XR'] },
  { name: '理光', en: 'Ricoh', aliases: ['RICOH', '理光'], snPrefixes: ['RC'] },
  { name: '京瓷', en: 'Kyocera', aliases: ['KYOCERA', '京瓷'], snPrefixes: ['KY'] },
  { name: '奔图', en: 'Pantum', aliases: ['PANTUM', '奔图'], snPrefixes: ['PT'] },
  { name: '中科曙光', en: 'Sugon', aliases: ['SUGON', '曙光', '中科曙光'], snPrefixes: ['SG'] },
  { name: '浪潮', en: 'Inspur', aliases: ['INSPUR', '浪潮'], snPrefixes: ['IN'] },
  { name: '新华三', en: 'H3C', aliases: ['NEWH3C', 'UNIS', '紫光'], snPrefixes: ['2102'] },
  { name: '锐捷', en: 'Ruijie', aliases: ['RUIJIE', '锐捷', 'RG'], snPrefixes: ['RG', 'G1'] },
  { name: '普联', en: 'TP-Link', aliases: ['TPLINK', '普联', 'TL'], snPrefixes: ['TP', 'TL'] },
  { name: '网件', en: 'Netgear', aliases: ['NETGEAR', '网件'], snPrefixes: ['NG'] },
  { name: '思科', en: 'Cisco', aliases: ['CISCO', '思科', 'LINKSYS'], snPrefixes: ['FOC', 'FCW', 'JAE'] },
  { name: '英特尔', en: 'Intel', aliases: ['INTEL', '英特尔', 'NUC'], snPrefixes: ['IN'] },
  { name: '超微', en: 'Supermicro', aliases: ['SUPERMICRO', '超微'], snPrefixes: ['SM'] },
  { name: '技嘉', en: 'Gigabyte', aliases: ['GIGABYTE', '技嘉', 'AORUS'], snPrefixes: ['GB'] },
  { name: '微星', en: 'MSI', aliases: ['MSI', '微星', 'MICROSTAR'], snPrefixes: ['MS'] },
  { name: '罗技', en: 'Logitech', aliases: ['LOGITECH', '罗技', 'LOGI'], snPrefixes: ['LG', 'LZ'] },
  { name: '雷蛇', en: 'Razer', aliases: ['RAZER', '雷蛇'], snPrefixes: ['RZ'] },
  { name: '微软', en: 'Microsoft', aliases: ['MICROSOFT', '微软', 'SURFACE'], snPrefixes: ['MS', '0'] },
  { name: '谷歌', en: 'Google', aliases: ['GOOGLE', '谷歌', 'PIXEL'], snPrefixes: ['G0'] },
  { name: '中兴通讯', en: 'ZTE', aliases: ['ZTE', 'ZTE CORPORATION'], snPrefixes: ['ZT'] },
  { name: '大华', en: 'Dahua', aliases: ['DAHUA', '大华'], snPrefixes: ['DH'] },
  { name: '海康威视', en: 'Hikvision', aliases: ['HIKVISION', '海康', '海康威视'], snPrefixes: ['HK'] },
  { name: '群晖', en: 'Synology', aliases: ['SYNOLOGY', '群晖'], snPrefixes: ['SY'] },
  { name: '威联通', en: 'QNAP', aliases: ['QNAP', '威联通'], snPrefixes: ['QN'] },
  { name: '西部数据', en: 'Western Digital', aliases: ['WESTERNDIGITAL', '西部数据', 'WD'], snPrefixes: ['WD', 'WCC'] },
  { name: '希捷', en: 'Seagate', aliases: ['SEAGATE', '希捷'], snPrefixes: ['ST', 'ZA'] },
  { name: '金士顿', en: 'Kingston', aliases: ['KINGSTON', '金士顿'], snPrefixes: ['KF', 'SA'] },
  { name: '山特', en: 'Santak', aliases: ['SANTAK', '山特'], snPrefixes: ['ST'] },
  { name: '施耐德', en: 'Schneider', aliases: ['SCHNEIDER', '施耐德', 'APC'], snPrefixes: ['AS'] },
  { name: '爱普生', en: 'Epson', aliases: ['EPSON CHINA'], snPrefixes: ['EP'] },
  { name: '兄弟中国', en: 'Brother', aliases: ['BROTHER CHINA'], snPrefixes: ['BR'] },
  { name: '松下', en: 'Panasonic', aliases: ['PANASONIC', '松下', 'TECHNICS'], snPrefixes: ['PA'] },
  { name: '东芝', en: 'Toshiba', aliases: ['TOSHIBA', '东芝', 'DYNABOOK'], snPrefixes: ['TO', 'XA'] },
  { name: '索尼', en: 'Sony', aliases: ['SONY', '索尼', 'VAIO'], snPrefixes: ['SO', 'C1'] },
  { name: '富士通', en: 'Fujitsu', aliases: ['FUJITSU', '富士通'], snPrefixes: ['FU'] },
  { name: '神舟', en: 'Hasee', aliases: ['HASEE', '神舟'], snPrefixes: ['HS'] },
  { name: '机械革命', en: 'Mechrevo', aliases: ['MECHREVO', '机械革命'], snPrefixes: ['MR'] },
  { name: '雷神', en: 'ThundeRobot', aliases: ['THUNDEROBOT', '雷神'], snPrefixes: ['TR'] },
  { name: '七彩虹', en: 'Colorful', aliases: ['COLORFUL', '七彩虹'], snPrefixes: ['CF'] },
  { name: '同方', en: 'Tsinghua Tongfang', aliases: ['TSINGHUA', '同方', '清华同方'], snPrefixes: ['TF'] },
  { name: '长城', en: 'Great Wall', aliases: ['GREATWALL', '长城'], snPrefixes: ['GW'] },
  { name: '海尔', en: 'Haier', aliases: ['HAIER', '海尔'], snPrefixes: ['HR'] },
  { name: 'TCL', en: 'TCL', aliases: ['TCL', '雷鸟'], snPrefixes: ['TC'] },
  { name: '创维', en: 'Skyworth', aliases: ['SKYWORTH', '创维'], snPrefixes: ['SW'] },
  { name: '海信', en: 'Hisense', aliases: ['HISENSE', '海信'], snPrefixes: ['HI'] },
  { name: '攀升', en: 'IPASON', aliases: ['IPASON', '攀升'], snPrefixes: ['IP'] },
  { name: '宁美', en: 'Ningmei', aliases: ['NINGMEI', '宁美'], snPrefixes: ['NM'] },
  { name: '中科可控', en: 'Suma', aliases: ['SUMA', '中科可控'], snPrefixes: ['SU'] },
  { name: '统信', en: 'UnionTech', aliases: ['UNIONTECH', '统信', 'UOS'], snPrefixes: ['UT'] },
  { name: '麒麟', en: 'Kylin', aliases: ['KYLIN', '麒麟'], snPrefixes: ['KL'] },
  { name: '虹光', en: 'Avision', aliases: ['AVISION', '虹光'], snPrefixes: ['AV'] },
  { name: '紫光', en: 'Unis', aliases: ['UNIS', '紫光', '清华紫光'], snPrefixes: ['UN'] },
];

/** 铭牌上常见但不应被当作品牌的噪声词 */
export const BRAND_NOISE = [
  'INPUT', 'OUTPUT', 'MODEL', 'MODELNO', 'SERIES', 'SERIAL', 'SERIALNO', 'SN', 'S/N',
  'MADEINCHINA', 'MADEIN', 'CHINA', 'TAIWAN', 'VIETNAM', 'RATED', 'VOLTAGE', 'POWER',
  'WARNING', 'CAUTION', 'WWW', 'HTTP', 'HTTPWWW', 'MADE', 'DESIGNED', 'ASSEMBLED',
  'MADEINCHINATAIWAN', 'CLASS', 'TYPE', 'PARTNO', 'P/N', 'PNO', 'REV', 'VERSION',
  'PRODUCT', 'COMPUTER', 'MONITOR', 'DISPLAY', 'LAPTOP', 'NOTEBOOK', 'NOTEBOOKCOMPUTER',
  'CERTIFIED', 'LIMITED', 'WARRANTY', 'MANUFACTURED', 'REGULATORY', 'CANADA', 'KOREA',
];
